config/routes.rb
Materis::Application.routes.draw do

  resources :oauth_applications

  use_doorkeeper
  resources :milestones

  get "reports/index"
  get "reports/activities"
  get "reports/employees_daily"
  get "reports/employee_day"
  get "reports/employees_time_range"
  get "reports/employee_range"
  get "reports/tasks"
  get "reports/task"
  get "reports/okrs"
  get "reports/get_selection_list"
  get "reports/employee_tasks"
  get "reports/worklogs"
  get "reports/day_log"
  get "reports/assignments"

  resources :work_logs do
    member do
      post 'delete_request'
      post 'ignore_request'
    end
  end

  get "calendar/index"
  get "calendar/monthly"
  get "calendar/day"
  get "calendar/week"
  resources :comments do
    member do
      get 'reply'
      post 'post_reply'
    end
  end

  resources :tasks do
    resources :comments
    member do
      post 'completion'
    end
    collection do
      get 'completed_index'
    end
  end

  resources :teams do
    get 'add_members'
    post 'add_members'
    collection do
      get 'get_member_list'
    end
  end

  get "home/index"
  get "home/dashboard"
  get "home/search"
  post "home/search"
  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}

  resources :projects, :path => 'departments' do
    get 'add_members'
    post 'add_members'
    collection do
      get 'get_member_list'
    end
    resources :teams
  end

  resources :jobs, :path => 'projects' do
    resources :comments
  end

  resources :users do
    resources :okrs do
      member do
        post 'approve'
      end
    end
    collection do
      get 'change_password'
      post 'change_password'
    end
  end

  namespace :api do
    namespace :v1 do
      get '/me' => "credentials#me"
    end
  end

  root 'home#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :source, :polymorphic=>true
  scope :active, -> {where(is_deleted: false)}

  validates_presence_of :user_id,:body,:source

  after_save :update_comment_count

  def update_comment_count
    source.update_attributes(:comments_count=>source.comments.active.count)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    if params[:task_id].present?
      @task = Task.find(params[:task_id])
      @comments = @task.comments.active
      @comment = @task.comments.new
    else
      @comments = Comment.active
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      @task = @comment.source
      @comments = @task.comments.active
      @comment = @task.comments.new
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end

  private
  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:source_id, :source_type, :body, :user_id, :task_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comments.erb
<%= render :partial => 'comments/form' %>
<% @comments.each do |comment| %>
    <div class="comments-panel">
      <div class="col-sm-1">
        <%= link_to image_tag(comment.user.image.icon), user_path(comment.user), :class => 'left' %>
      </div>
      <div class="col-sm-11">
        <div class="row">
          <%= link_to comment.user.name, user_path(comment.user), :class => 'comment-name' %></span> <span class="date"><%= comment.created_at.max_diff %></span>
        </div>
        <div class="row">
          <span class="comment-body"><%= comment.body %></span>
        </div>
      </div>
    </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment, :remote => true, :data => {:abide => true}) do |f| %>
    <%= f.hidden_field :source_id, :value => @comment.source_id %>
    <%= f.hidden_field :source_type, :value => @comment.source_type %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <div class="field">
      <%= f.text_field :body, :placeholder => 'Add comment',:required => '' %>
    </div>
<% end %>

app/views/comments/create.js.erb
<% unless @comment.errors.present? %>
$('.comments-<%= @task.id %>').html("<%= escape_javascript(render :partial => 'comments/comments') %>")
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Source</th>
      <th>Source type</th>
      <th>Body</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.source_id %></td>
        <td><%= comment.source_type %></td>
        <td><%= comment.body %></td>
        <td><%= comment.user_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/post_reply.js.erb
<% unless @comment.errors.present? %>
$('.comments-<%= @task.id %>').html("<%= escape_javascript(render :partial => 'comments/comments') %>")
<% end %>

app/views/comments/reply.js.erb
<% unless @comment.errors.present? %>
$('.comments-<%= @task.id %>').html("<%= escape_javascript(render :partial => 'comments/comments') %>")
<% end %>