config/routes.rb
Materis::Application.routes.draw do

  resources :oauth_applications

  use_doorkeeper
  resources :milestones

  get "reports/index"
  get "reports/activities"
  get "reports/employees_daily"
  get "reports/employee_day"
  get "reports/employees_time_range"
  get "reports/employee_range"
  get "reports/tasks"
  get "reports/task"
  get "reports/okrs"
  get "reports/get_selection_list"
  get "reports/employee_tasks"
  get "reports/worklogs"
  get "reports/day_log"
  get "reports/assignments"

  resources :work_logs do
    member do
      post 'delete_request'
      post 'ignore_request'
    end
  end

  get "calendar/index"
  get "calendar/monthly"
  get "calendar/day"
  get "calendar/week"
  resources :comments do
    member do
      get 'reply'
      post 'post_reply'
    end
  end

  resources :tasks do
    resources :comments
    member do
      post 'completion'
    end
    collection do
      get 'completed_index'
    end
  end

  resources :teams do
    get 'add_members'
    post 'add_members'
    collection do
      get 'get_member_list'
    end
  end

  get "home/index"
  get "home/dashboard"
  get "home/search"
  post "home/search"
  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}

  resources :projects, :path => 'departments' do
    get 'add_members'
    post 'add_members'
    collection do
      get 'get_member_list'
    end
    resources :teams
  end

  resources :jobs, :path => 'projects' do
    resources :comments
  end

  resources :users do
    resources :okrs do
      member do
        post 'approve'
      end
    end
    collection do
      get 'change_password'
      post 'change_password'
    end
  end

  namespace :api do
    namespace :v1 do
      get '/me' => "credentials#me"
    end
  end

  root 'home#index'
end

app/models/task.rb
class Task < ActiveRecord::Base
  extend FriendlyId
  friendly_id :id

  belongs_to :user
  belongs_to :team
  belongs_to :milestone
  belongs_to :project
  belongs_to :job
  has_many :comments, :as => :source, dependent: :destroy


  before_create :add_tracker_id

  after_save :update_team_task_count
  before_update :update_completion

  belongs_to :root_task, :class_name => "Task", :foreign_key => "task_id"
  has_many :sub_tasks, :class_name => "Task", :foreign_key => "task_id", dependent: :destroy

  scope :active, -> { where(is_deleted: false) }
  scope :root, -> { where(task_id: nil) }
  scope :sub, -> { where("task_id IS NOT NULL") }
  scope :pending, -> { where(status: 'active') }
  scope :completed, -> { where(status: 'completed') }
  scope :searchable_for_user, lambda { |user| where("id in (?) OR id in (?) OR project_id in (?)  OR team_id in (?)", user.task_ids, user.assignment_ids, user.project_ids, user.team_ids) }


  def updatable_by_user(user)

    return true if user.admin_team_ids.include?(team_id)
    return true if user.project_ids.include?(project_id)
  end

  def time_to_end
    if end_date.to_date == Date.today
      'Due today'
    elsif end_date <= Date.today
      'Ended on '+end_date.strftime('%d %B %Y')
    elsif end_date <= 7.day.from_now
      rem = (end_date.to_date - Date.today.to_date).to_i
      "#{rem} #{'day'.pluralize(rem)} left"
    else
      'Due '+end_date.strftime('%d %B %Y')
    end
  end


  def update_team_task_count
    team.update_attributes(:pending_tasks => team.tasks.active.pending.count)
  end

  def add_tracker_id
    self.tracker_id = Task.unscoped.last.try(:tracker_id).to_i + 1
  end

  def timestamp
    created_at.strftime('%d %B %Y %H:%M:%S')
  end


  def update_completion
    if self.status? && self.status_changed? && self.status_change[1] == 'completed' and self.status_change[0] == 'active'
      self.completed_on = Time.now
    elsif self.status? && self.status_changed? && self.status_change[1] == 'active' and self.status_change[0] == 'completed'
      self.completed_on = nil
    end
  end

  def task_status
    if self.status == 'completed'
      '<span class="tag tag-members">Completed</span>'
    else
      '<span class="tag tag-managers">Pending</span>'
    end
  end
end

app/models/team.rb
class Team < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  belongs_to :project
  has_and_belongs_to_many :jobs
  has_many :team_members, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_many :users, :through => :team_members
  has_many :leads, -> { where role: 'lead' }, class_name: 'TeamMember', dependent: :destroy
  has_many :team_leads, :through => :leads, :source => :user, dependent: :destroy
  has_many :members, -> { uniq }, :through => :team_members, :source => :user, dependent: :destroy

  validates_presence_of :name, :code, :project_id

  # default_scope { where.not(is_deleted: true).order("teams.name ASC") }

  scope :active, -> { where(status: 'active') }
  scope :archived, -> { where(is_deleted: true) }
  scope :unarchived, -> { where(is_deleted: false) }
  scope :available, -> do
    if project.is_deleted?
      where(Team.archived)
    else
      where(Team.unarchived)
    end
  end

  after_save :update_project_team_count
  after_destroy :update_project_team_count


  def update_project_team_count
    project.update_attributes(:team_count => project.teams.active.count)
    project.update_attributes(:team_count => project.teams.active.count)
  end

  def self.for_user(user)
    teams = Team.where("project_id IN (?) OR id IN (?)",user.project_ids,(user.admin_team_ids + user.team_ids).uniq)
  end

  def self.admind_by_user(user)
    teams = Team.where("project_id IN (?) OR id IN (?)",user.project_ids,user.admin_team_ids.uniq)
  end

  def self.assignable_by_user(user)
    teams = Team.where(project_id:(user.project_ids+user.admin_teams.collect(&:project_id).uniq))
  end

  def total_tasks
    return self.tasks.count
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  load_and_authorize_resource
  #load_and_authorize_resource :task, :through => [:team,:task], :shallow => true

  # GET /tasks
  # GET /tasks.json
  def index
    #@tasks = current_user.assignments
    @tasks = current_user.watching_tasks.pending.paginate(page: params[:page], per_page: 10)
    @fin_tasks = current_user.watching_tasks.completed.paginate(page: params[:page], per_page: 10) unless params[:page]
  end

  def completed_index
    #@tasks = current_user.assignments
    @fin_tasks = current_user.watching_tasks.completed.paginate(page: params[:page], per_page: 10)
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @tasks = current_user.assigned_and_written_tasks.pending.paginate(page: params[:page], per_page: 10)
    @fin_tasks = current_user.watching_tasks.completed.paginate(page: params[:page], per_page: 10) unless params[:page]
    @team = @task.team
    @project = @team.project
    @sub_tasks = @task.sub_tasks
    @comment = @task.comments.new
  end

# GET /tasks/new
  def new
    @root_task = Task.find(params[:task_id]) if params[:task_id].present?
    @team = @root_task.team if params[:task_id].present?
    @jobs = Job.all
    @task = @root_task.present? ? @root_task.sub_tasks.new : Task.new
    @tasks = current_user.watching_tasks.pending.paginate(page: params[:page], per_page: 10)
    @task.start_date = Time.now
    @task.end_date = Time.now
    if params[:team_id].present?
      @team = Team.find(params[:team_id])
      @task.team_id = @team.id if @team.present?
      @task.project_id = @team.project_id if @team.present?
    end

    if params[:project_id].present?
      @job = Job.find(params[:project_id])
      @milestone = @job.milestones.first
      @task.job_id = @job.id if @job.present?
      @milestones = @job.milestones
      @milestone = Milestone.find(params[:milestone_id])
      @teams = @job.teams
    end

    @grouped_milestones = @milestones.inject({}) do |options, milestone|
      (options[milestone.name] ||= []) << [milestone.name, milestone.id]
      options
    end
    @grouped_teams = @teams.inject({}) do |options, team|
      (options[team.project.name] ||= []) << [team.name, team.id]
      options
    end
    @grouped_jobs = @jobs.inject({}) do |options, job|
      (options[job.name] ||= []) << [job.name, job.id]
      options
    end
    @team ||= @teams.first
    if @team.present?
    if (current_user.admin_teams.include?(@team) || current_user.project_ids.include?(@team.project_id))
      @users = @team.members
    else
      @users = @team.team_leads
    end
    else
      redirect_to root_path, :alert => 'You have no access to a team in order to assign a task.'
    end
  end

  # GET /tasks/1/edit
  def edit
    @projects = Project.active

    @jobs = Job.all
    @task.job_id = @job.id if @job.present?
    @tasks = current_user.watching_tasks.pending.paginate(page: params[:page], per_page: 10)
    @job = Job.find(@task.job_id)
    @milestone = @task.milestone
    @milestones = @job.milestones

    @team ||= @task.team
    @teams = Team.assignable_by_user(current_user).includes(:project)

    @grouped_teams = @teams.inject({}) do |options, team|
      (options[team.project.name] ||= []) << [team.name, team.id]
      options
    end
    @grouped_milestones = @milestones.inject({}) do |options, milestone|
      (options[milestone.name] ||= []) << [milestone.name, milestone.id]
      options
    end
    @grouped_jobs = @jobs.inject({}) do |options, job|
      (options[job.name] ||= []) << [job.name, job.id]
      options
    end

    @users = @team.try(&:members)
    start_date = @task.start_date
    end_date = @task.end_date
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.project_id = @task.team.project_id if @task.team.present?
    if task_params[:job_id].present?
      @job = Job.find(task_params[:job_id])
    end

    respond_to do |format|
      if @task.save
        format.html { redirect_to @job, notice: 'Task was successfully created.' }
        format.json { render action: 'show', status: :created, location: @task }
      else
        format.html { render action: 'new' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    @job = Job.find(@task.job_id)
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @job, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end

  def completion
    @task = Task.find(params[:id])
    if request.post?
      @task.update_attributes(:completed_on => params[:task][:completed_on].to_time, :status => 'completed') if (params[:task] && params[:task][:completed_on])
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def task_params
    params.require(:task).permit(:name, :description, :start_date, :task_id, :end_date, :project_id, :team_id, :user_id, :job_id, :milestone_id, :tracker_id, :priority, :comments_count, :status, :completed_on, :key_result_ids => [], :user_ids => [])
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_completed_task_page.erb
<% if @fin_tasks.present? %>
  <% current_user.teams.unarchived.uniq.each do |team| %>
    <% team.tasks.completed.each do |task| %>
      <%= link_to task_path(task),:remote=>true do %>
          <div class="card transition task-card task task-<%= task.id %>">
            <div class="name">
              <%= task.name %>
            </div>
            <div class="date end-<%= (task.end_date <= 7.day.from_now && task.end_date >= Date.today) ? 'soon' : 'low' %>">
              <%= task.time_to_end %>
              <div class="right">
                <%= raw("<div class='icon icon-author'></div>") if task.user_id == current_user.id %>
              </div>
            </div>
            <div class="team">
              <%= task.team.name %>
            </div>
          </div>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/tasks/_completed_tasks.erb
<% if @fin_tasks.present? %>
  <% current_user.teams.unarchived.uniq.each do |team| %>
    <% team.tasks.completed.each do |task| %>
      <%= link_to task_path(task),:remote=>true do %>
          <div class="card transition task-card task task-<%= task.id %>">
            <div class="name">
              <%= task.name %>
            </div>
            <div class="date end-<%= (task.end_date <= 7.day.from_now && task.end_date >= Date.today) ? 'soon' : 'low' %>">
              <%= task.time_to_end %>
              <div class="right">
                <%= raw("<div class='icon icon-author'></div>") if task.user_id == current_user.id %>
              </div>
            </div>
            <div class="team">
              <%= task.team.name %>
            </div>
          </div>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/tasks/_completion.erb
<div  data-dropdown-content="" style="position: static;">
  <% if task.status == 'completed' %>
      <div class="row">
        <div class="col-sm-12">
          <div class="project-card no-border relative">
            <div class="card-block shadowed">
              Completed on
              <%= task.completed_on.strftime('%d/%m/%Y %H:%M') %>
            </div>
          </div>
        </div>
      </div>
  <% else %>
      <%= form_for :task, :url => completion_task_path(task.id), :remote => true do |f| %>
          <div class="row">
            <div class="col-sm-12">
              <div class="project-card no-border relative">
                <div class="card-block shadowed">
                  <%= f.label :completed_on %>
                  <%= f.text_field :completed_on, :value => Time.now.strftime('%d/%m/%Y %H:%M') %>
                  <button class="button">Done</button>
                </div>
              </div>
            </div>
          </div>
      <% end %>
  <% end %>
</div>

app/views/tasks/_form.html.erb
<% if @team.present? %>
    <%= form_for @task, :html => {:class => 'form-horizontal task-form', :multipart => true, :data => {:abide => true}} do |f| %>
        <div class="pane3-padding">
          <div class="row">
            <div class="col-sm-12">
              <div class="project-card">
                <div class="card-block">
                  <div class="form-content form-below">
                    <%= f.hidden_field :task_id, :value => @root_task.id if @root_task.present? %>
                    <%= f.hidden_field :team_id, :value => @root_task.team_id if @root_task.present? %>
                    <%= f.hidden_field :project_id, :value => @root_task.project_id if @root_task.present? %>
                    <%= f.hidden_field :job_id, :value => @root_task.job_id if @root_task.present? %>
                    <%= f.hidden_field :user_id, :value => current_user.id %>

                    <%= build_validated_field('task', 'name', 'Title', 'Cannot be blank', '', 'text', @task.name) %>
                    <%= build_field('task', 'description', 'Description', 'text_area', @task.description) %>

                    <% unless @root_task.present? %>
                      <%= f.label :team_id, 'Team' %>
                      <%= select_tag "task[team_id]", grouped_options_for_select(@grouped_teams, @team.id) %>
                    <% end %>

                    <% unless @root_task.present? %>
                      <%= f.label :job_id, 'Job' %>
                      <%= select_tag "task[job_id]", options_for_select([[@job.name, @job.id]])%>
                    <% end %>

                    <% unless @root_task.present? %>
                      <%= f.label :milestone_id, 'Milestone' %>
                      <%= select_tag "task[milestone_id]", options_for_select([[@milestone.name, @milestone.id]]), :id => "select_milestone"%>
                    <% end %>

                    <%= f.label :start_date, 'Start Date' %>
                    <%= text_field_tag("task[start_date]", @task.start_date, :class => '', :required => '', :pattern => '', :placeholder => 'Start Date', :id => 'start_date') %>
                    <%= f.label :end_date, 'End Date' %>
                    <%= text_field_tag("task[end_date]", @task.end_date, :class => '', :required => '', :pattern => '', :placeholder => 'End Date', :id => 'end_date') %>

                    <%= f.label :status, 'Status' %>
                    <%= select_tag('task[status]', options_for_select([['Pending', 'active'], ['Completed', 'completed']], @task.status)) %>

                    <div class="priority-selector">
                      <%= build_validated_select('task', 'priority', 'Priority', 'Should select at least one', '', false, @task.priority, ['Low', 'Medium', 'High', 'Showstopper']) %>
                    </div>
                    <br>
                    <br>
                  </div>
                </div>
                <div class="pane3-padding">
                  <div class="right">
                    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                                jobs_path, :class => 'button alert' %>
                    <%= f.submit nil, :class => 'button success', data: {disable_with: "Saving"} %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
    <% end %>
<% else %>
    <div class="message">
      You have no access to a team in order to assign a task.
    </div>
<% end %>

<script type="text/javascript">
    window.location = '#pane3'
    $('select').not('.select_add').select2({'width': '100%'});


    $(document).ready(function () {

        $('#start_date').datetimepicker({
            timepicker:false,
            formatDate:'Y-m-d',
            minDate:'<%= @milestone.start_date.strftime("%Y-%m-%d") %>',
            maxDate:'<%= @milestone.end_date.strftime("%Y-%m-%d") %>'
        });
        $('#end_date').datetimepicker({
            timepicker:false,
            formatDate:'Y-m-d',
            minDate:'<%= @milestone.start_date.strftime("%Y-%m-%d") %>',
            maxDate:'<%= @milestone.end_date.strftime("%Y-%m-%d") %>'
        });
    });
</script>

app/views/tasks/_pending_tasks.erb
<% @tasks.each do |task| %>
    <%= link_to task_path(task),:remote=>true do %>
        <div class="card transition task-card task task-<%= task.id %>">
          <div class="name">
            <%= task.name %>
          </div>
          <div class="date end-<%= (task.end_date <= 7.day.from_now && task.end_date >= Date.today) ? 'soon' : 'low' %>">
            <%= task.time_to_end %>
            <div class="right">
              <%= raw("<div class='icon icon-author'></div>") if task.user_id == current_user.id %>
              <%= raw("<div class='icon icon-assignee'></div>") if task.user_ids.include?(current_user.id) %>
            </div>
          </div>
          <div class="team">
            <%= task.team.name %>
          </div>
        </div>
    <% end %>
<% end %>

app/views/tasks/_show.erb
<div class="row">
  <div class="col-sm-12">
    <div class="project-card">
      <div class="card-block">
        <div class="row">
          <div class="col-sm-10">
            <div class="project-title">
              <%= task.name %>
            </div>
          </div>
          <div class="col-sm-2">
            <div class="project-title right date">
              <%= task.created_at.strftime('%d %B %Y') %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="project-card">
      <div class="card-block">
        <div class="row">
          <div class="col-sm-4">
            <div class="project-title">
              <div class="project-code">Priority</div>
            </div>
          </div>
          <div class="col-sm-8">
            <div class="project-code right">
              <span class="task-priority priority-<%= task.priority %>">
                  <%= task.priority %>
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-sm-12 min-panel-size">
      <div class="project-card min-panel-size">
        <div class="card-block">
          <div class="row centered">
            <div class="col-sm-4 right-border">
              <div class="project-code">Created By</div>
              <span class="date"> <%= task.user.name %></span>
            </div>
            <div class="col-sm-4 right-border">
              <div class="project-code">Start Date</div>
              <span class="date"> <%= task.start_date.strftime('%d %B %Y') %></span>
            </div>
            <div class="col-sm-4">
              <div class="project-code">End Date</div>
              <span class="date"> <%= task.end_date.strftime('%d %B %Y') %></span>
            </div>
          </div>
        </div>
        <hr>
        <div class="card-block">
          <div class="row">
            <div class="col-sm-12">
              <div class="project-code"><%= task.description %></div>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-12">
    <div class="card-header">
      <div class="comments-link comments-<%= task.id %> ">
        <% if @comment.present? %>
            <%= render :partial => 'comments/form' %>
        <% end %>
        <%= link_to "#{task.comments_count.to_i} #{'comment'.pluralize(task.comments_count.to_i)}", task_comments_path(task), :remote => true %>
      </div>
    </div>

    <% if @sub_tasks.present? %>
      <% @sub_tasks.each_with_index do |task, i| %>
          <%= render :partial => 'tasks/sub_task', :locals => {:task => task, :count => i+1} %>
      <% end %>
    <% end %>

  </div>
</div>

<script type="text/javascript">
    $('.task.card').removeClass('active')
    $('.task-<%= task.id %>').addClass('active')
    $(window).scrollTop($('#pane3').offset().top)
    $(document).foundation();
</script>

app/views/tasks/_show_detailed.erb
<div class="row">
  <div class="col-sm-12 pane3-padding">
    <%= render :partial=>'tasks/show',:locals=>{:task=>task,:project=>project,:team=>team}  %>
  </div>
</div>

app/views/tasks/_sub_task.erb
<div class="subtask">
  Subtask
  <%= count %>:
  <%= link_to task.name,task_path(task) %>

  <div class="info">
    <div class="icon icon-author"></div> Added by
    <em><%= task.user.name %></em>
    on
    <em><%= task.created_at.strftime('%d %B %Y') %></em>
      <span class="task-priority priority-<%= task.priority %>">
        Priority: <%= task.priority %>
      </span>
  </div>

  <div class="info">
    <div class="icon icon-timer"></div> Start date
    <em><%= task.start_date.strftime('%d %B %Y') %></em>
    End date
    <em><%= task.end_date.strftime('%d %B %Y') %></em>
  </div>

  <div class="info">
    <div class="icon icon-assignee"></div> Assigned to
    <em>
      <% task.users.each_with_index do |u, i| %>
          <%= link_to u.name, user_path(u) %>
          <%= i+1 != task.users.count ? "," : '' %>
      <% end %>
    </em>
  </div>
</div>

app/views/tasks/_task_job_list.erb
<div class="card-header text-uppercase text-muted">
  <div class="row">
    <div class="col-sm-4">Task Name</div>
    <div class="col-sm-2">Team</div>
    <div class="col-sm-2">Milestone</div>
    <div class="col-sm-2">Status</div>
    <div class="col-sm-1">Due</div>
    <div class="col-sm-1"></div>
  </div>
</div>
<% tasks.active.each do |task| %>
    <div class="items-list">
      <div class="il-item">
        <div class="media">
          <div class="media-body">
            <div class="text-muted">
              <div class="row">
                <div class="col-md-4">
                  <span style="color: #43b968"><a href="#" data-reveal-id="modal-<%= task.id %>"><%= task.name.capitalize %></a></span>
                  <br>
                  <div class="date">
                    <b>Created By:</b> <%= task.user.name %>
                  </div>
                </div>
                <div class="col-md-2">
                  <span class="tag tag-teams" style="background-color: <%= task.team.color %>"><%= task.team.name %></span>
                </div>
                <div class="col-md-2">
                  <%= task.milestone.name %>
                </div>
                <div class="col-md-2">
                  <%= raw(task.task_status) %>
                </div>
                <div class="col-md-1">
                  <div class="date end-<%= (task.end_date <= 7.day.from_now && task.end_date >= Date.today) ? 'soon' : 'low' %>">
                    <%= task.time_to_end %>
                  </div>
                </div>
                <div class="col-md-1">
                  <span class="media-heading right">
                    <% if can? :edit, @job %>
                      <a href="#" data-options="align:left" data-dropdown="taskdrop-<%= task.id %>" aria-controls="drop-<%= task.id %>" aria-expanded="false">
                        <i class="material-icons md-18">more_vert</i>
                      </a>
                      <ul id="taskdrop-<%= task.id %>" data-dropdown-content class="f-dropdown" tabindex="-1">
                        <li>
                          <i class="fi-pencil"></i> <%= link_to "Edit Task", edit_task_path(task) %>
                        </li>
                        <li>
                          <i class="fi-x"></i> <%= link_to "Delete Task", task_path(task),:method=>:delete, data: { confirm: 'Are you sure you want to delete this task?' } %>
                        </li>
                      </ul>
                    <% end %>
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div id="modal-<%= task.id %>" class="reveal-modal small" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
      <%= render :partial => 'tasks/show', :locals => {:task => task} %>
      <a class="close-reveal-modal" aria-label="Close">&#215;</a>
    </div>
<% end %>

app/views/tasks/_task_list.erb
<div class="pane2-meta">
  <div class="title">My tasks</div>
  <dl class="tabs right" data-tab >
    <dd class="active clear-tab"><a href="#pending">
      Pending
    </a></dd>
    <dd class="clear-tab"><a href="#completed">
      Completed
    </a></dd>
  </dl>
</div>

  <div class="data-container">
    <div class="tabs-content">
      <div class="content active" id="pending">

        <div class="task-list" id="my-tasks">
          <div class="pane2-content scroll2watch">
          <div id="paginator" class="paginator task-paginator">
            <%= render :partial => 'tasks/task_page' %>
          </div>
          <div id="infinite-scrolling" class="scroll-loop">
            <%= will_paginate(@tasks, :params => {:controller => "tasks", :action => "index"}) %>
          </div>
          </div>
        </div>

      </div>
      <div class="content" id="completed">
        <div class="task-list" id="my-tasks">
          <div class="pane2-content scroll2watch this">
            <div id="paginator"  class="paginator fin-task-paginator">
              <%= render :partial => 'tasks/completed_tasks' %>
            </div>
            <div id="infinite-scrolling" class="scroll-loop">
              <%= will_paginate(@fin_tasks, :params => {:controller => "tasks", :action => "completed_index"}) %>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
<script type="text/javascript">
    infiniteScroll()
</script>

app/views/tasks/_task_page.erb
<% current_user.teams.unarchived.uniq.each do |team| %>
    <% team.tasks.pending.each do |task| %>
      <%= link_to task_path(task),:remote=>false do %>
          <div class="card transition task-card task task-<%= task.id %>">
            <div class="name">
              <%= task.name %>
            </div>
            <div class="date end-<%= (task.end_date <= 7.day.from_now && task.end_date >= Date.today) ? 'soon' : 'low' %>">
              <%= task.time_to_end %>
              <div class="right">
                <%= raw("<div class='icon icon-author'></div>") if task.user_id == current_user.id %>
              </div>
            </div>
            <div class="team">
              <%= task.team.name %>
            </div>
          </div>
      <% end %>
  <% end %>
<% end %>

app/views/tasks/completion.js.erb
$('.completion-area.drop-task-<%= @task.id %>').html("<%= escape_javascript(render :partial => 'tasks/completion',:locals => {:task => @task}) %>")

app/views/tasks/index.html.erb
<%= content_for :pane2 do %>
  <%= render :partial => 'tasks/task_list' %>
<% end %>
<script type="text/javascript">
    window.location = '#pane2'
</script>

app/views/tasks/index.js.erb
$('.task-paginator').append('<%= j render 'tasks/task_page' %>');
<% if @tasks.next_page %>
$('#pending .pagination').replaceWith('<%= j will_paginate @tasks %>');
<% else %>
$(window).off('scroll');
$('#pending .pagination').remove();
<% end %>
window.location = '#pane2'