config/routes.rb
Materis::Application.routes.draw do

  resources :oauth_applications

  use_doorkeeper
  resources :milestones

  get "reports/index"
  get "reports/activities"
  get "reports/employees_daily"
  get "reports/employee_day"
  get "reports/employees_time_range"
  get "reports/employee_range"
  get "reports/tasks"
  get "reports/task"
  get "reports/okrs"
  get "reports/get_selection_list"
  get "reports/employee_tasks"
  get "reports/worklogs"
  get "reports/day_log"
  get "reports/assignments"

  resources :work_logs do
    member do
      post 'delete_request'
      post 'ignore_request'
    end
  end

  get "calendar/index"
  get "calendar/monthly"
  get "calendar/day"
  get "calendar/week"
  resources :comments do
    member do
      get 'reply'
      post 'post_reply'
    end
  end

  resources :tasks do
    resources :comments
    member do
      post 'completion'
    end
    collection do
      get 'completed_index'
    end
  end

  resources :teams do
    get 'add_members'
    post 'add_members'
    collection do
      get 'get_member_list'
    end
  end

  get "home/index"
  get "home/dashboard"
  get "home/search"
  post "home/search"
  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}

  resources :projects, :path => 'departments' do
    get 'add_members'
    post 'add_members'
    collection do
      get 'get_member_list'
    end
    resources :teams
  end

  resources :jobs, :path => 'projects' do
    resources :comments
  end

  resources :users do
    resources :okrs do
      member do
        post 'approve'
      end
    end
    collection do
      get 'change_password'
      post 'change_password'
    end
  end

  namespace :api do
    namespace :v1 do
      get '/me' => "credentials#me"
    end
  end

  root 'home#index'
end

app/models/job.rb
class Job < ActiveRecord::Base
  has_many :tasks, dependent: :destroy
  has_many :milestones, dependent: :destroy
  has_many :custom_fields
  belongs_to :user
  has_and_belongs_to_many :teams

  accepts_nested_attributes_for :custom_fields, reject_if: :all_blank, allow_destroy: true

  validates_presence_of :name, :code, :color, :team_ids
  validates_uniqueness_of :code

  mount_uploader :image, ImageUploader

  scope :active, -> {where(is_deleted: false)}
  scope :archived, -> {where(is_deleted: true)}

  def total_tasks
    return self.tasks.count
  end
  def completed_tasks
    return self.tasks.completed.count
  end
  def incomplete_tasks
    return self.tasks.pending.count
  end
  def project_status
    (self.tasks.count == 0) ? 0 : ((self.tasks.completed.count.to_f / self.tasks.count.to_f) * 100).to_i
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  extend FriendlyId
  friendly_id :employee_code

  mount_uploader :image, ImageUploader

  has_many :project_managers, dependent: :destroy
  has_many :projects, :through => :project_managers
  has_many :team_members, dependent: :destroy
  has_many :teams, :through => :team_members
  has_many :admin_teams, :through => :projects, :source => :teams
  has_many :leads, -> { where role: 'lead' }, class_name: 'TeamMember'
  has_many :admin_teams, :through => :leads, :source => :team #,:foreign_key=>'user_id'
  has_many :joined_projects, :through => :teams, :source => :project
  has_many :comments
  has_many :reporting_managers, dependent: :destroy
  has_many :jobs
  has_many :tasks
  has_many :managers, :through => :reporting_managers, :class_name => 'User'
  has_many :reporting_employees, :class_name => "ReportingManager", :foreign_key => "manager_id", dependent: :destroy
  has_many :users, :through => :reporting_employees, :class_name => 'User', :foreign_key => "user_id"
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable, :lastseenable, :omniauthable, :omniauth_providers => [:google_oauth2, :fluxapp]
  scope :active, -> { where(is_deleted: false) }
  scope :by_name, -> { order("users.name ASC") }
  scope :manager_user, -> {where("role in (?)",["admin","Manager"])}

  validates_presence_of :name, :nickname
  validate :email, :presence => true, :uniqueness => true
  validate :employee_code, :presence => true, :uniqueness => true

  before_update :ensure_manager_exists

  def admin?
    role.downcase == 'admin'
  end

  def manager?
    role.downcase.in?(['manager', 'admin'])
  end

  def employee?
    role.downcase == 'employee'
  end

  def accessible_users
    unless manager?
      project_user_ids = projects.collect(&:project_member_ids).flatten
      team_member_ids = admin_teams.collect(&:user_ids).flatten
      managing_users = user_ids
      user_ids = [id]
      user_ids = user_ids + project_user_ids + team_member_ids +user_ids
      user_ids = user_ids.uniq
      users = User.where(id: user_ids).by_name
    else
      users= User.by_name
    end
  end

  def assigned_and_written_tasks
    Task.where(id: (task_ids).uniq)
  end

  def watching_tasks
    Task.active.where("id IN (?) OR team_id IN (?)", (task_ids).uniq, admin_team_ids)
  end

  def log_viewable_tasks
    if manager?
      Task.active
    else
      Task.active.where("id IN (?) OR team_id IN (?)", (task_ids + assignment_ids).uniq, admin_team_ids)
    end
  end

  def ensure_manager_exists
      if User.manager_user.count == 1 and self.changes.present? and self.changes[:role].present?
          if self.changes[:role][0] == "admin" and self.changes[:role][1] == "Manager"
            self.role = "admin"
            return true
          elsif (self.changes[:role][0] == "admin" and self.changes[:role][1] == "Employee" ) or (self.changes[:role][0] == "Manager" and self.changes[:role][1] == "Employee")
            errors[:base] << "Atleast one manager required"
            return false
          else
            return true
          end
      end
  end

  def online?
    updated_at > 10.minutes.ago
  end

  def seen_at
    if self.online?
      '<span class="tag tag-members">Online</span>'
    else
      '<span class="tag tag-managers">Offline</span>'
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
    @jobs = Job.all
    @job = @jobs.first unless @jobs.empty?
  end

  def show
    @jobs = Job.all
    @teams = @job.teams
  end

  def new
    @jobs = Job.all
    @team = Team.new
    @teams = Team.active
  end

  def edit
    @jobs = Job.all
    @teams = Team.active
  end

  def create
    @job = Job.new(job_params)
    @teams = Team.active
    @job.user_id = current_user.id
    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render action: 'show', status: :created, location: @job }
      else
        format.html { render action: 'new' }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @teams = Team.active
    @job = Job.find params[:id]
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end

  private
  def set_job
    @job = Job.find(params[:id])
  end

  def job_params
    params.fetch(:job).permit(:name, :code, :description, :is_deleted, :color, :image, :start_date, :end_date, :status, :team_ids => [], custom_fields_attributes: [:id, :name, :value, :_destroy])
  end
end

app/views/jobs/_form.html.erb
<%= form_for @job, :html => {:class => 'form-horizontal', :multipart => true, :data => {:abide => true}} do |f| %>
  <div class="row">
    <div class="col-lg-12">
      <div class="col-lg-12">
        <div class="pane3-padding">
          <div class="project-card">
            <div class="card-block">
              <div class="form-content form-below">
                <% if @job.errors.any? %>
                    <div id="error_explanation">
                      <% @job.errors.full_messages.each do |msg| %>
                          <li><%= msg %></li>
                      <% end %>
                      </ul>
                    </div>
                <% end %>
                <%= build_validated_field('job', 'name', 'Title', 'Cannot be blank', '[a-zA-Z]+', 'text',@job.name) %>
                <%= build_validated_field('job', 'code', 'Code', 'Cannot be blank', '[a-zA-Z]+', 'text',@job.code) %>
                <%= build_field('job', 'description', 'Description', 'text_area',@job.description) %>
                <%= build_field('job', 'image', 'Image', 'file',@job.image) %>

                <%= build_validated_field('job', 'start_date', 'Start Date', 'Cannot be blank', '', 'date_field', @job.start_date) %>
                <%= build_validated_field('job', 'end_date', 'End Date', 'Cannot be blank', '', 'date_field', @job.end_date) %>

                <%= f.label :team_ids, 'Teams' %>
                <%= f.select :team_ids, @teams.map { |x| [x.name, x.id] }, {}, {:multiple => true} %>

                <%= f.label :status, 'Status' %>
                <%= select_tag('job[status]', options_for_select([['Active', 'active'], ['Completed', 'completed']], @job.status)) %>

                <%= f.label 'Project Color' %>
                <div class="colorPicker">
                  <input <%= if @job.color == '#fe4365' then 'checked="checked"' end %> class="red" id="hat-color-red" name="job[color]" value="#fe4365" type="radio">
                  <label class="red" for="hat-color-red"></label>

                  <input <%= if @job.color == '#83af9b' then 'checked="checked"' end %> class="green" id="hat-color-green" name="job[color]" value="#83af9b" type="radio">
                  <label class="green" for="hat-color-green"></label>

                  <input <%= if @job.color == '#355c7d' then 'checked="checked"' end %> class="blue" id="hat-color-blue" name="job[color]" value="#355c7d" type="radio">
                  <label class="blue" for="hat-color-blue"></label>

                  <input <%= if @job.color == '#6c5b7b'  then 'checked="checked"' end %> class="violet" id="hat-color-violet" name="job[color]" value="#6c5b7b" type="radio">
                  <label class="violet" for="hat-color-violet"></label>

                  <input <%= if @job.color == '#363636' then 'checked="checked"' end %> class="gray" id="hat-color-gray" name="job[color]" value="#363636" type="radio">
                  <label class="gray" for="hat-color-gray"></label>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-12">
        <div class="pane3-padding">
          <div class="project-card">
            <div class="card-header text-uppercase">Project Fields</div>
            <div class="card-block">
              <div class="form-content form-below">
                <%= f.fields_for :custom_fields do |field| %>
                    <%= render 'custom_fields/custom_fields', f: field %>
                <% end %>
                <div class="col-lg-12">
                  <%= link_to_add_association raw('<span class="fi-plus"></span> New Field'), f, :custom_fields, :partial => 'custom_fields/custom_fields', :class => 'button' %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="pane3-padding">
    <div class="right">
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  jobs_path, :class => 'button alert' %>
      <%= f.submit ( f.object.new_record? ? "Create Project" : "Update Project"), :class => 'button success', data: {disable_with: "Saving"} %>
    </div>
  </div>
<% end %>
<script type="text/javascript">
    window.location = '#pane3'
</script>

app/views/jobs/_job_list.erb
<div class="pane2-meta">
  <div class="title">Projects</div>
  <div class="right white">
    <% if can? :create, Job %>
        <%= link_to raw('<span class="fi-plus"></span> Add Project'), new_job_path, :remote => false, :class => 'button' %>
    <% end %>
  </div>
</div>

<div class="pane2-content">
  <% jobs.each do |jobs| %>
    <%= link_to job_path(jobs), :remote => true do %>
      <div class="project card-transparent">
        <div class="small-2 columns vertical-align">
          <%= image_tag(jobs.image.icon) %>
        </div>
        <div class="small-5 columns vertical-align">
          <div class="project-list-title"><%= truncate(jobs.name, :length => 30).titleize  %></div>
        </div>
        <div class="small-2 columns vertical-align"></div>
        <div class="small-3 columns vertical-align">
          <div class="button <%= jobs.status %>"><%= jobs.status.titleize %></div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/jobs/_show.erb
<div class="pane3-padding team-show">
  <div class="expanded row">
    <div class="col-sm-3">
      <div class="project-card">
        <div class="profile-avatar">
          <%= image_tag(job.image.thumbnail) %>
        </div>
        <div class="card-block">
          <div class="row">
            <div class="col-sm-10">
              <div class="project-title">
                <div class="col-sm-1">
                  <div style="background-color: <%= job.color %>; height: 10px; width: 10px"></div>
                </div>
                <%= truncate(job.name) %>
              </div>
              <div class="project-code"><%= job.code %></div>
            </div>
            <div class="col-sm-2">
              <% if can? :edit, job %>
                  <a href="#" data-options="align:left" data-dropdown="drop1" class="dropdown right">
                    <i class="material-icons md-18">more_vert</i>
                  </a>
                  <ul id="drop1" data-dropdown-content class="f-dropdown">
                    <li>
                      <i class="fi-pencil"></i> <%= link_to "Edit", edit_job_path(job) %>
                    </li>
                    <li>
                      <i class="fi-x"></i> <%= link_to "Delete", job_path(job),:method=>:delete, data: { confirm: 'Are you sure you want to delete this project?' } %>
                    </li>
                  </ul>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="project-card">
        <div class="items-list">
          <div class="card-header text-uppercase">Project Fields</div>
          <% job.custom_fields.each do |field| %>
            <div class="il-item">
              <div class="media">
                <div class="media-body">
                  <h6 class="media-heading"><%= field.name %></h6>
                  <span class="text-muted"><%= field.value %></span>
                </div>
              </div>
            </div>
          <% end %>
          <div class="card-header text-uppercase">Task Stats</div>
          <div class="il-item">
            <div class="media">
              <div class="media-body">
                <h6 class="media-heading">Total Tasks</h6>
                <span class="text-muted"><%= job.total_tasks %> task(s) have been created</span>
              </div>
            </div>
          </div>
          <div class="il-item">
            <div class="media">
              <div class="media-body">
                <h6 class="media-heading">Completed Tasks</h6>
                <span class="text-muted"><%= job.completed_tasks %> task(s) have been completed</span>
              </div>
            </div>
          </div>
          <div class="il-item">
            <div class="media">
              <div class="media-body">
                <h6 class="media-heading">Incomplete Tasks</h6>
                <span class="text-muted">There are <%= job.incomplete_tasks %> incomplete tasks</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-9">
      <div class="row">
        <div class="project-card">
          <div class="card-header text-uppercase">Description</div>
          <div class="items-list">
            <div class="il-item">
                <div class="media">
                  <div class="media-body">
                    <h6 class="media-heading"><%= job.description %></h6>
                  </div>
                </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="project-card">
          <div class="data-container">
            <dl class="tabs" data-tab>
              <dd><a href="#job-team-list">
                Team <span class="tag tag-members"><%= job.teams.count %></span>
              </a></dd>
              <dd><a href="#job-task-list">
                Tasks <span class="tag tag-managers"><%= job.total_tasks %></span>
              </a></dd>
              <dd><a href="#job-milestone-list">
                Milestones <span class="tag tag-members"><%= job.milestones.count %></span>
              </a></dd>
            </dl>
            <div class="tabs-content">
              <div class="content active" id="job-team-list">
                <div class="card-header"></div>
                <%= render :partial => 'teams/team_list', :locals => {:teams => @teams.present? ? @job.teams : @job.teams} %>
              </div>
              <div class="content" id="job-task-list">
                <div class="card-header"></div>
                <%= render :partial => 'tasks/task_job_list', :locals => {:tasks => @job.tasks} %>
              </div>
              <div class="content" id="job-milestone-list">
                <div class="card-header text-uppercase"></div>
                <%= render :partial => 'milestones/milestone_list', :locals => {:milestones => @job.milestones} %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="project-card">
          <div class="card-header">
            <%= job.name %> Timeline
            <div class="right">
              <% if can? :edit, @job %>
                  <%= link_to raw('<span class="fi-plus"></span> Add Milestone'), new_milestone_path(:job_id => job.id), :remote => false, :class => 'tag-milestone' %>
              <% end %>
            </div>
          </div>
          <div class="items-list">
            <div class="il-item">
              <a class="text-black" href="#">
                <div class="media">
                  <div class="media-body">
                    <div id="chart_div"></div>
                  </div>
                </div>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
    $('.team-card').removeClass('active')
    $('.team-<%= job.id %>').addClass('active')

    google.charts.load('current', {'packages':['gantt']});
    google.charts.setOnLoadCallback(drawGanttChart);

    function drawGanttChart() {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Task ID');
        data.addColumn('string', 'Task Name');
        data.addColumn('date', 'Start Date');
        data.addColumn('date', 'End Date');
        data.addColumn('number', 'Duration');
        data.addColumn('number', 'Percent Complete');
        data.addColumn('string', 'Dependencies');
        data.addRows([
              ['<%= job.name %>', '<%= job.name %>',
                new Date('<%= @job.start_date.strftime("%Y-%m-%d") %>'), new Date('<%= @job.end_date.strftime("%Y-%m-%d") %>'), null,  <%= job.project_status %>,  null],
            <% job.milestones.each do |milestone| %>
              <% milestone_status = (milestone.tasks.count == 0) ? 0 : ((milestone.tasks.completed.count.to_f / milestone.tasks.count.to_f) * 100).to_i %>
              ['<%= milestone.name %>', '<%= milestone.name %>',
                  new Date('<%= milestone.start_date.strftime("%Y-%m-%d") %>'), new Date('<%= milestone.end_date.strftime("%Y-%m-%d") %>'), null, <%= milestone_status %>, null],
            <% end %>
        ]);

        var options = {
            gantt: {
                criticalPathEnabled: false,
                barHeight: 15,
                barCornerRadius: 0
            }
        };

        var chart = new google.visualization.Gantt(document.getElementById('chart_div'));
        chart.draw(data, options);
    }
</script>

app/views/jobs/edit.html.erb
<%= content_for :pane2 do %>
    <%= render :partial => 'jobs/job_list', :locals => {:jobs => @jobs} %>
<% end %>
<%= content_for :pane3 do %>
    <%= render :partial => 'form' %>
<% end %>
<script type="text/javascript">
    window.location = '#pane3'
</script>

app/views/jobs/index.html.erb
<%= content_for :pane2 do %>
    <%= render :partial => 'jobs/job_list', :locals => {:jobs => @jobs} %>
<% end %>
<%= content_for :pane3 do %>
    <% if @job.present? %>
        <%= render :partial => 'jobs/show', :locals => {:job => @job} %>
    <% end %>
<% end %>
<script type="text/javascript">
    window.location = '#pane2'
</script>

app/views/jobs/new.html.erb
<%= content_for :pane2 do %>
    <%= render :partial => 'jobs/job_list', :locals => {:jobs => @jobs} %>
<% end %>
<%= content_for :pane3 do %>
    <%= render :partial => 'form' %>
<% end %>
<script type="text/javascript">
    window.location = '#pane3'
</script>

app/views/jobs/new.js.erb
$('.pane3').html("<%= escape_javascript(render :partial => 'projects/form',:locals=>{:project=>@project}) %>")
$(document).foundation({
    tab: {
        callback: function (tab) {
        }
    }
});
window.location = '#pane3'

app/views/jobs/show.html.erb
<%= content_for :pane2 do %>
    <%= render :partial => 'jobs/job_list', :locals => {:jobs => @jobs} %>
<% end %>

<%= content_for :pane3 do %>
    <% if @job.present? %>
        <%= render :partial => 'jobs/show', :locals => {:job => @job} %>
    <% end %>
<% end %>
<script type="text/javascript">
    window.location = '#pane3'
</script>

app/views/jobs/show.js.erb
$('.pane3').html("<%= escape_javascript(render :partial => 'jobs/show',:locals=>{:job=>@job}) %>")
$(document).foundation({
    tab: {
        callback: function (tab) {
        }
    }
});
window.location = '#pane3'