config/routes.rb
Materis::Application.routes.draw do

  resources :oauth_applications

  use_doorkeeper
  resources :milestones

  get "reports/index"
  get "reports/activities"
  get "reports/employees_daily"
  get "reports/employee_day"
  get "reports/employees_time_range"
  get "reports/employee_range"
  get "reports/tasks"
  get "reports/task"
  get "reports/okrs"
  get "reports/get_selection_list"
  get "reports/employee_tasks"
  get "reports/worklogs"
  get "reports/day_log"
  get "reports/assignments"

  resources :work_logs do
    member do
      post 'delete_request'
      post 'ignore_request'
    end
  end

  get "calendar/index"
  get "calendar/monthly"
  get "calendar/day"
  get "calendar/week"
  resources :comments do
    member do
      get 'reply'
      post 'post_reply'
    end
  end

  resources :tasks do
    resources :comments
    member do
      post 'completion'
    end
    collection do
      get 'completed_index'
    end
  end

  resources :teams do
    get 'add_members'
    post 'add_members'
    collection do
      get 'get_member_list'
    end
  end

  get "home/index"
  get "home/dashboard"
  get "home/search"
  post "home/search"
  devise_for :users, :controllers => {:omniauth_callbacks => "users/omniauth_callbacks"}

  resources :projects, :path => 'departments' do
    get 'add_members'
    post 'add_members'
    collection do
      get 'get_member_list'
    end
    resources :teams
  end

  resources :jobs, :path => 'projects' do
    resources :comments
  end

  resources :users do
    resources :okrs do
      member do
        post 'approve'
      end
    end
    collection do
      get 'change_password'
      post 'change_password'
    end
  end

  namespace :api do
    namespace :v1 do
      get '/me' => "credentials#me"
    end
  end

  root 'home#index'
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :teams, dependent: :destroy
  has_many :jobs
  has_many :tasks, dependent: :destroy
  has_many :project_managers, dependent: :destroy
  has_many :users,:through=>:project_managers,:after_remove => :update_user_project_count
  has_many :team_members, :through => :teams, dependent: :destroy
  has_many :project_members, :through=>:team_members, :source=>:user, dependent: :destroy

  validates_presence_of :name, :code
  validates_uniqueness_of :code

  mount_uploader :image, ImageUploader

  default_scope{ order("projects.name ASC")}

  scope :active, -> {where(is_deleted: false)}
  scope :archived, -> {where(is_deleted: true)}

  def members
    return project_members.active.uniq
  end

  def update_user_project_count(pm)
    pm.update_attributes(:admin_projects_count=>pm.projects.count)
  end

  def update_numbers
    update_attributes(:team_count=>self.teams.count)
  end
  def total_tasks
    return self.tasks.count
  end
  def completed_tasks
    return self.tasks.completed.count
  end
  def incomplete_tasks
    return self.tasks.pending.count
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :archive]
  load_and_authorize_resource

  def index
    @projects = Project.active
    @project = @projects.first unless @projects.empty?

    @archived_projects = Project.archived
    @archived_project = @archived_projects.first unless @projects.empty?
  end

  def show
    @projects = Project.active
    @teams = @project.teams
    @managers = @project.users.by_name
    @members = @project.members.where('').map{|x| x}.sort{|a,b| a.name<=>b.name}
  end

  def add_members
    @teams = Team.for_user(current_user)
    @team = Team.find(params[:team_id])
    @users = User.active.by_name
    @members = @team.members.by_name
  end

  def new
    @projects = Project.active
    @project = Project.new
    @users= User.active
  end

  def edit
    @projects = Project.active
    @users= User.active
  end

  def create
    @project = Project.new(project_params)
    @users= User.active

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @users= User.active
    @project = Project.find params[:id]
    if params[:project][:is_deleted]
      @project.update_attribute(:is_deleted, params[:project][:is_deleted])
      @project.teams.update_all(:is_deleted => params[:project][:is_deleted])
      @project.tasks.update_all(:is_deleted => params[:project][:is_deleted])
    end
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  def get_member_list
    team = Team.find(params[:team_id])
    if (current_user.admin_teams.include?(team) || current_user.project_ids.include?(team.project_id))
      @users = team.members.by_name
    else
      @users = team.team_leads.by_name
    end
    start_date = params[:start_date].to_date
    end_date = params[:end_date].to_date
    @kr_ids = Task.find(params[:task_id]).key_result_ids unless params[:task_id].blank?
    @kr_ids ||= []
    @key_results = team.key_results.where('key_results.start_date <= ? && key_results.end_date >= ?', end_date, start_date).group_by(&:user_id)
  end

  private
  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit!
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_active_projects.erb
<% projects = Project.active if projects.nil? %>
<% projects.each do |project| %>
    <%= link_to project_path(project), :remote => false do %>
        <div class="project card-transparent transition prj-<%= project.id %>">
          <div class="cols ths">
            <%= image_tag(project.image.icon) %>
          </div>
          <div class="cols">
            <div class="project-title"><%= project.name %></div>
            <div class="text">
              <%= "#{project.team_count} #{'team'.pluralize(project.team_count)}" %>
              <%= "#{project.member_count} #{'member'.pluralize(project.member_count)}" %>
            </div>
            <div class="text">
              <%= project.website %>
            </div>
          </div>
        </div>
    <% end %>
<% end %>

app/views/projects/_archived_project.erb
<% projects = Project.archived if projects.nil? %>
<% projects.each do |project| %>
    <%= link_to project_path(project), :remote => true do %>
        <div class="project card-transparent transition prj-<%= project.id %>">
          <div class="cols ths">
            <%= image_tag(project.image.icon) %>
          </div>
          <div class="cols">
            <div class="project-title"><%= project.name %></div>
            <div class="text">
              <%= "#{project.team_count} #{'team'.pluralize(project.team_count)}" %>
              <%= "#{project.member_count} #{'member'.pluralize(project.member_count)}" %>
            </div>
            <div class="text">
              <%= project.website %>
            </div>
          </div>
        </div>
    <% end %>
<% end %>

app/views/projects/_archived_projects.erb
<% projects = Project.archived if projects.nil? %>
<% projects.each do |project| %>
    <%= link_to project_path(project), :remote => true do %>
        <div class="project card-transparent transition prj-<%= project.id %>">
          <div class="cols ths">
            <%= image_tag(project.image.icon) %>
          </div>
          <div class="cols">
            <div class="project-title"><%= project.name %></div>
            <div class="text">
              <%= "#{project.team_count} #{'team'.pluralize(project.team_count)}" %>
              <%= "#{project.member_count} #{'member'.pluralize(project.member_count)}" %>
            </div>
            <div class="text">
              <%= project.website %>
            </div>
          </div>
        </div>
    <% end %>
<% end %>

app/views/projects/_form.html.erb
<%= form_for @project, :html => {:class => 'form-horizontal', :multipart => true, :data => {:abide => true}} do |f| %>
        <div class="pane3-padding">
          <div class="row">
            <div class="col-sm-12">
              <div class="project-card">
                <div class="card-block">
                  <div class="form-content form-below">
                    <% if @project.errors.any? %>
                        <div id="error_explanation">
                          <% @project.errors.full_messages.each do |msg| %>
                              <li><%= msg %></li>
                          <% end %>
                          </ul>
                        </div>
                    <% end %>
                    <%= build_validated_field('project', 'name', 'Title', 'Cannot be blank', '[a-zA-Z]+', 'text',@project.name) %>
                    <%= build_validated_field('project', 'code', 'Code', 'Cannot be blank', '[a-zA-Z]+', 'text',@project.code) %>
                    <%= build_field('project', 'website', 'Url', 'text',@project.website) %>
                    <%= build_field('project', 'description', 'Description', 'text_area',@project.description) %>
                    <%= build_field('project', 'image', 'Image', 'file',@project.image) %>
                    <%= f.check_box :remove_image %>
                    Remove Image<br>
                    <%= f.label :user_ids, 'Managers' %>
                    <%= f.select :user_ids,@users.map{|x| [x.name,x.id]},{},{:multiple=>true} %>
                    <%= f.label 'Department Color' %>

                    <div class="colorPicker">
                      <input <%= if @project.color == '#fe4365' then 'checked="checked"' end %> class="red" id="hat-color-red" name="project[color]" value="#fe4365" type="radio">
                      <label class="red" for="hat-color-red"></label>

                      <input <%= if @project.color == '#83af9b' then 'checked="checked"' end %> class="green" id="hat-color-green" name="project[color]" value="#83af9b" type="radio">
                      <label class="green" for="hat-color-green"></label>

                      <input <%= if @project.color == '#355c7d' then 'checked="checked"' end %> class="blue" id="hat-color-blue" name="project[color]" value="#355c7d" type="radio">
                      <label class="blue" for="hat-color-blue"></label>

                      <input <%= if @project.color == '#6c5b7b'  then 'checked="checked"' end %> class="violet" id="hat-color-violet" name="project[color]" value="#6c5b7b" type="radio">
                      <label class="violet" for="hat-color-violet"></label>

                      <input <%= if @project.color == '#363636' then 'checked="checked"' end %> class="gray" id="hat-color-gray" name="project[color]" value="#363636" type="radio">
                      <label class="gray" for="hat-color-gray"></label>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="pane3-padding">
          <div class="right">
            <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                        projects_path, :class => 'button alert' %>
            <%= f.submit ( f.object.new_record? ? "Create Department" : "Update Department"), :class => 'button success', data: {disable_with: "Saving"} %>
          </div>
        </div>
<% end %>


<script type="text/javascript">
    window.location = '#pane3'
</script>

app/views/projects/_list_projects.erb
<div class="card-header text-uppercase"></div>
<% projects.each do |project| %>
  <div class="items-list">
    <div class="il-item">
      <div class="media">
        <div class="media-body">
          <div class="text-muted">
            <div class="row">
              <div class="col-sm-1">
                <%= image_tag(project.image.icon) %>
              </div>
              <div class="col-sm-5">
                <h6 class="media-heading">
                  <%= link_to project.name, project_path(project), :remote => false, :class => 'grey-link' %>
                </h6>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/projects/_project_list.erb
<div class="pane2-meta">
  <div class="title">Departments</div>
  <dl class="tabs right" data-tab >
    <dd class="active clear-tab"><a href="#active">
      Active
    </a></dd>
    <dd class="clear-tab"><a href="#archived">
      Archived
    </a></dd>
  </dl>
</div>

<div class="data-container">
  <div class="tabs-content">
    <div class="content active" id="active">
      <div class="task-list" id="my-tasks">
        <div class="pane2-content scroll2watch">
          <% if can? :create, Project %>
              <%= link_to 'Create New Department', new_project_path, :remote => false, :class => 'dashed_link transition' %>
          <% end %>
          <div id="paginator" class="paginator task-paginator">
            <%= render :partial => 'projects/active_projects' %>
          </div>
        </div>
      </div>
    </div>
    <div class="content" id="archived">
      <div class="task-list" id="my-tasks">
        <div class="pane2-content scroll2watch this">
          <div id="paginator"  class="paginator fin-task-paginator">
            <%= render :partial => 'projects/archived_projects' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/_project_page.erb
<% projects = Project.active if projects.nil? %>
<% projects.each do |project| %>
    <%= link_to project_path(project), :remote => false do %>
        <div class="project card-transparent transition prj-<%= project.id %>">
          <div class="cols ths">
            <%= image_tag(project.image.icon) %>
          </div>
          <div class="cols">
            <div class="project-title"><%= project.name %></div>
            <div class="text">
              <%= "#{project.team_count} #{'team'.pluralize(project.team_count)}" %>
              <%= "#{project.member_count} #{'member'.pluralize(project.member_count)}" %>
            </div>
            <div class="text">
              <%= project.website %>
            </div>
          </div>
        </div>
    <% end %>
<% end %>

app/views/projects/_show.erb
<div class="pane3-padding">
  <div class="row">
    <div class="col-sm-3">
      <div class="project-card">
        <div class="profile-avatar">
          <%= image_tag(project.image.thumbnail) %>
        </div>
        <div class="card-block">
          <div class="row">
            <div class="col-sm-6">
              <div class="project-title">
                <%= project.name %>
              </div>
              <div class="project-code"><%= project.code %></div>
              <div class="project-website"><%= project.website %></div>
            </div>
            <div class="col-sm-6">
              <% if can? :manage, @project %>
                  <a href="#" data-options="align:left" data-dropdown="drop1" class="dropdown right">
                    <i class="material-icons md-18">more_vert</i>
                  </a>
                  <ul id="drop1" data-dropdown-content class="f-dropdown">
                    <li>
                      <% if can? :edit, @project %>
                          <% if defined? project %>
                              <i class="fi-plus"></i> <%= link_to 'New Team', new_project_team_path(project), :remote => false %>
                          <% end %>
                      <% end %>
                    </li>
                    <hr>
                    <li>
                      <i class="fi-pencil"></i> <%= link_to "Edit Department", edit_project_path(@project) %>
                    </li>
                    <li>
                      <i class="fi-page-copy"></i> <%= link_to "Copy Department URL", '#', :id => 'copy-url' %>
                    </li>
                    <hr>
                    <li>
                      <% if @project.is_deleted? %>
                        <i class="fi-refresh"></i> <%= link_to("Restore Department", project_path(@project, "project[is_deleted]" => 0), :method => :put, data: {confirm: "Are you sure you want to restore this department?"}) %>
                      <% else %>
                        <i class="fi-archive"></i> <%= link_to("Archive Department", project_path(@project, "project[is_deleted]" => 1), :method => :put, data: {confirm: "Are you sure you want to archive this department?"}) %>
                      <% end %>
                    </li>
                    <li>
                      <i class="fi-x"></i> <%= link_to "Delete Department", project_path(@project), :method => :delete, data: {confirm: "Are you sure you want to delete this department?"} %>
                    </li>
                  </ul>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <div class="project-card">
        <div class="card-header text-uppercase">Stats</div>
        <div class="items-list">
          <div class="il-item">
            <a class="text-black" href="#">
              <div class="media">
                <div class="media-body">
                  <h6 class="media-heading">Total Tasks</h6>
                  <span class="text-muted"><%= project.total_tasks %> task(s) have been created</span>
                </div>
              </div>
            </a>
          </div>
          <div class="il-item">
            <a class="text-black" href="#">
              <div class="media">
                <div class="media-body">
                  <h6 class="media-heading">Completed Tasks</h6>
                  <span class="text-muted"><%= project.completed_tasks %> task(s) have been completed</span>
                </div>
              </div>
            </a>
          </div>
          <div class="il-item">
            <a class="text-black" href="#">
              <div class="media">
                <div class="media-body">
                  <h6 class="media-heading">Incomplete Tasks</h6>
                  <span class="text-muted">There are <%= project.incomplete_tasks %> incomplete tasks</span>
                </div>
              </div>
            </a>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-9">
      <div class="row">
        <div class="project-card">
          <div class="card-header text-uppercase">Description</div>
          <div class="items-list">
            <div class="il-item">
              <a class="text-black" href="#">
                <div class="media">
                  <div class="media-body">
                    <h6 class="media-heading"><%= project.description %></h6>
                  </div>
                </div>
              </a>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="project-card mb-0">
          <div class="data-container">
            <dl class="tabs" data-tab>
              <dd class="active"><a href="#project-teams">
                Teams <span class="tag tag-members"><%= project.team_count %></span>
              </a></dd>
              <dd><a href="#project-members">
                Members <span class="tag tag-members"><%= project.members.count %></span>
              </a></dd>
              <dd><a href="#project-tasks">
                Tasks <span class="tag tag-members"><%= project.total_tasks %></span>
              </a></dd>
            </dl>

            <div class="tabs-content">
              <div class="content active" id="project-teams">
                <div class="card-header"></div>
                <%= render :partial => 'teams/team_list', :locals => {:project => @project, :teams => @teams.present? ? @teams : @project.teams} %>
              </div>
              <div class="content" id="project-members">
                <div class="card-header"></div>
                <%= render :partial => 'users/user_list', :locals => {:users => @members.present? ? @members : @project.members} %>
              </div>
              <div class="content" id="project-tasks">
                <div class="card-header"></div>
                <%= render :partial => 'tasks/task_project_list', :locals => {:tasks => @project.tasks} %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
    $('.project.card').removeClass('active')
    $('.prj-<%= project.id %>').addClass('active')

    $('#copy-url').click(function (event) {
        CopyLink('<%=request.url %>')
        event.preventDefault();
    });
</script>

app/views/projects/edit.html.erb
<%= content_for :pane2 do %>
    <%= render :partial => 'projects/project_list', :locals => {:projects => @projects} %>
<% end %>
<%= content_for :pane3 do %>
    <%= render :partial => 'form' %>
<% end %>
<script type="text/javascript">
    window.location = '#pane3'
</script>

app/views/projects/index.html.erb
<%= content_for :pane2 do %>
    <%= render :partial => 'projects/project_list', :locals => {:projects => @projects} %>
<% end %>

<%= content_for :pane3 do %>
    <% if @project.present? %>
        <%= render :partial => 'projects/show', :locals => {:project => @project} %>
    <% end %>
<% end %>
<script type="text/javascript">
    window.location = '#pane2'
</script>

app/views/projects/new.html.erb
<%= content_for :pane2 do %>
    <%= render :partial => 'projects/project_list', :locals => {:projects => @projects} %>
<% end %>
<%= content_for :pane3 do %>
    <%= render :partial => 'form' %>
<% end %>
<script type="text/javascript">
    window.location = '#pane3'
</script>

app/views/projects/show.html.erb
<%= content_for :pane2 do %>
    <%= render :partial => 'projects/project_list', :locals => {:projects => @projects} %>
<% end %>

<%= content_for :pane3 do %>
    <% if @project.present? %>
        <%= render :partial => 'projects/show', :locals => {:project => @project} %>
    <% end %>
<% end %>
<script type="text/javascript">
    window.location = '#pane3'
</script>

app/views/projects/show.js.erb
$('.pane3').html("<%= escape_javascript(render :partial => 'projects/show',:locals=>{:project=>@project}) %>")
$(document).foundation({
    tab: {
        callback: function (tab) {
        }
    }
});
window.location = '#pane3'